name: sastra_ebooks
description: Sastra E-Books

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# need to add version numbers!
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  shimmer: ^1.1.1
  rflutter_alert: ^1.0.3
  intl: ^0.16.1
  dio: ^3.0.9
  material_design_icons_flutter: ^4.0.5345
  flutter_svg: ^0.17.4
  path_provider: ^1.6.10
  animated_text_kit: ^2.2.0
#  flutter_pdfview: ^1.0.2+3
  upi_india: ^2.1.2
  http: ^0.12.1
  url_launcher: ^5.4.10
  flutter_offline: ^0.3.0
  cached_network_image: ^2.2.0+1

  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.7

#  flutter_full_pdf_viewer: ^1.0.6
#  native_pdf_view: ^3.6.2
#  pdf_viewer_plugin: ^1.0.0
  flutter_keyboard_size: 0.1.2+2
  flutter_fullpdfview: any
  flutter_pdfview: ^1.0.2+3
  flutter_cache_manager: ^1.4.1
  outline_material_icons: ^0.1.1

  #firebase
  firebase: ^7.3.0
  firebase_storage: ^3.1.6
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  provider: ^4.1.2
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  cupertino_icons: ^0.1.3
  flutter_keyboard_visibility: ^3.2.1
  workmanager: ^0.2.3
  keyboard_utils: 1.2.4

  keyboard_visibility:
    git:
      url: https://github.com/alex-thmv/flutter_keyboard_visibility.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/helpers/
    - assets/icons/
